/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisiblePane.java
 *
 * Created on Dec 30, 2012, 8:22:50 PM
 */
package subliminal.ui;

import java.awt.Dimension;

import subliminal.common.Constants;
import subliminal.common.settingsVariables;

/**
 * Used as base pane for scrolling text
 * http://docs.oracle.com/javase/tutorial/uiswing/misc/trans_shaped_windows.html
 * http://today.java.net/pub/a/today/2008/03/18/translucent-and-shaped-swing-windows.html
 * @author t0763ss
 */
public class VisiblePane extends javax.swing.JFrame {

    static VisiblePane instance= null;
    /** Creates new form VisiblePane */
    private VisiblePane() {
        initComponents();
//        AWTUtilities.setWindowOpacity(this, 0.05F);
//        this.setOpacity(opacity);
//        AWTUtilities.setWindowOpaque(this, false);        
        initSettings();
    }
    
    public static VisiblePane getInstance(){
        if(instance==null)
            instance=new VisiblePane();
        return instance;
    }
    
    public void initSettings() {
        VisiblePane.lblMessage.setFont(settingsVariables.getInstance().getFont());
        VisiblePane.lblMessage.setForeground(settingsVariables.getInstance().getForeground());
        VisiblePane.lblMessage.setBackground(settingsVariables.getInstance().getBackground());        
        System.out.println("settingsVariables.getInstance().getOnTop()  "+ settingsVariables.getInstance().getOnTop());
        VisiblePane.lblMessage.repaint();
        Dimension d = VisiblePane.lblMessage.getSize();
        System.out.println("Lable Size " +d.width + " - " + d.height);
//        d.setSize(d.width, d.height);
        //set size from settings form
        d.setSize(settingsVariables.getInstance().getMsgWidth(),
                settingsVariables.getInstance().getMsgWidth());
        VisiblePane.lblMessage.setSize(d);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        if (settingsVariables.getInstance().getMsgDisplayType().equals(Constants.MSG_DISPLAY_TYPE_FLSHNIG)){
            lblMessage = new javax.swing.JLabel("à¤¸à¤¤à¥�à¤¯à¥‡à¤¨ à¤¶à¤¿à¤‚à¤ªà¥€");
        } else {
            lblMessage = new ScrollJLabel("à¤¸à¤¤à¥�à¤¯à¥‡à¤¨ à¤¶à¤¿à¤‚à¤ªà¥€");
            Thread t = new Thread((ScrollJLabel) lblMessage);
            t.start();
            t.setName(this.getClass().getName());
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusable(false);
        setFocusableWindowState(false);
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMessage.setText("Subliminal Message");
        lblMessage.setToolTipText("This is a Subliminal Message");
        lblMessage.setAutoscrolls(true);
        lblMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(lblMessage))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
    System.out.println("mouse entered");
}//GEN-LAST:event_formMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisiblePane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisiblePane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisiblePane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisiblePane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VisiblePane().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables

}